version: '3.5'

services:
  dscience:
    image: dscience
    ports:
      - 8888:8888
    volumes:
      - .:/model  # map this current directory with /usr/src/api in the docker container
    command: jupyter-notebook --allow-root
